Revert "[nrf fromlist] cmake: Port build scripts to support multi-image"
NordicPlayground/fw-nrfconnect-tinycbor pull request #2
Opened 2019-11-15 08:45 UTC by tejlmand

This PR introduces the use of the new principle for creating multi image build.

It reverts the only nordic specific commit, so instead of merging this PR, I suggests that we simply upmerge our fork and drop all Nordic only commits.
Alternatively, we start following upstream SHA in our manifest.

-------
This reverts commit 86d5ed5dd544b107d2d0882961a19c2c6cb06572.

Commit is reverted as part of new multi image approach where ${IMAGE}
is no longer needed.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

2019-11-15 14:36 UTC, SebastianBoe requested changes
NACK

WIP

2019-11-18 15:48 UTC, mbolivar commented
Since this PR means we have zero diff from upstream, I think we should just tag our current manifest-rev so it never gets lost for old versions, and simply point at upstream zephyrproject-rtos/tinycbor (revision `zephyr`, NOT `master`) directly from now on.

2019-11-19 10:32 UTC, tejlmand commented
Closing as: NordicPlayground/fw-nrfconnect-nrf#1508
now points upstream

2019-11-19 10:32 UTC, tejlmand commented
Closing as: NordicPlayground/fw-nrfconnect-nrf#1508
now points upstream

2019-11-19 10:32 UTC, closed without merging